name: Rust build and run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  linux-run-cli-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Build
      run: cargo build --verbose
    - name: Run testfile#1
      run: cargo run -- -c "./test_file/test1.tds" && cargo run -- -e "./test_file/test1.tdc"
    - name: Run testfile#2
      run: cargo run -- -c "./test_file/test2.tds" && cargo run -- -e "./test_file/test2.tdc"
    - name: Run testfile#3
      run: cargo run -- -c "./test_file/test3.tds" && cargo run -- -e "./test_file/test3.tdc"
    - name: Run testfile#4
      run: cargo run -- -c "./test_file/test4.tds" && cargo run -- -e "./test_file/test4.tdc" --create-answer "./test_file/test4.py"
    - name: Run testfile#5
      run: cargo run -- -c "./test_file/github-only/test5.tds" && cargo run -- -e "./test_file/github-only/test5.tdc"
    - name: Run testfile#6
      run: cargo run -- -c "./test_file/github-only/test6.tds" && cargo run -- -e "./test_file/github-only/test6.tdc" --create-answer "python ./test_file/github-only/test6.py"
    - name: Run testfile#7
      run: |
        cd ./test_file/github-only/
        mkdir output
        cargo run -- -c "./test7.tds" && cargo run -- -e "./test7.tdc" -n "10" --output-dir "./output" --filename-format "test7_**"
        python ./test7-checker.py


  windows-run-cli-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Build
      run: cargo build --verbose
    - name: Run testfile#1
      run: cargo run -- -c "./test_file/test1.tds" && cargo run -- -e "./test_file/test1.tdc"
    - name: Run testfile#2
      run: cargo run -- -c "./test_file/test2.tds" && cargo run -- -e "./test_file/test2.tdc"
    - name: Run testfile#3
      run: cargo run -- -c "./test_file/test3.tds" && cargo run -- -e "./test_file/test3.tdc"
    - name: Run testfile#4
      run: cargo run -- -c "./test_file/test4.tds" && cargo run -- -e "./test_file/test4.tdc" --create-answer "./test_file/test4.py"
    - name: Run testfile#5
      run: cargo run -- -c "./test_file/github-only/test5.tds" && cargo run -- -e "./test_file/github-only/test5.tdc"
    - name: Run testfile#6
      run: cargo run -- -c "./test_file/github-only/test6.tds" && cargo run -- -e "./test_file/github-only/test6.tdc" --create-answer "python ./test_file/github-only/test6.py"
    - name: Run testfile#7
      run: |
        cd ./test_file/github-only/
        mkdir output
        cargo run -- -c "./test7.tds" && cargo run -- -e "./test7.tdc" -n "10" --output-dir "./output" --filename-format "test7_**"
        python ./test7-checker.py
