name: Rust build and run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  run-cli-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run testfile#1
      run: cargo run -- -c "./test_file/test1.tds" && cargo run -- -e "./test_file/test1.tdc"
    - name: Run testfile#2
      run: cargo run -- -c "./test_file/test2.tds" && cargo run -- -e "./test_file/test2.tdc"
    - name: Run testfile#3
      run: cargo run -- -c "./test_file/test3.tds" && cargo run -- -e "./test_file/test3.tdc"